version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./apps:/var/www/html
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./apps:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
