server {
<<<<<<< HEAD
   charset utf-8;
   client_max_body_size 128M;
listen 80; ## listen for ipv4
   #listen [::]:80 default_server ipv6only=on; ## listen for ipv6
server_name app-frontend.dev;
   root /var/www/html;
   index index.php;
access_log  /var/log/nginx/frontend-access.log;
   error_log   /var/log/nginx/frontend-error.log;
location / {
       # Redirect everything that isn't a real file to index.php
       try_files $uri $uri/ /index.php$is_args$args;
   }
# uncomment to avoid processing of calls to non-existing static files by Yii
   #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
   #    try_files $uri =404;
   #}
   #error_page 404 /404.html;
location ~ \.php$ {
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_pass   phpfpm:9000;
       try_files $uri =404;
   }
location ~ /\.(ht|svn|git) {
       deny all;
   }
}
=======
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html index.htm;
    client_max_body_size 1000M;  

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
>>>>>>> 66525a0762f58bb4c1e750eea8130e28dc88c763
